from enum import Enum

MAX_PLAYERS = 5

MONEY_IN_BANK = 50

COINS_TO_CALL_COUP = 10

COUP_CARD_CODE = "e3"

ONE_INCOME_CARD_CODE = "e1"

class ActionType(str, Enum):
  INCOME = 'INCOME'
  FOREIGN_AID = 'FOREIGN_AID'
  COUP = 'COUP'
  TAX = 'TAX'
  ASSASSINATE = 'ASSASSINATE'
  EXCHANGE = 'EXCHANGE'
  STEAL = 'STEAL'


class EffectType(str, Enum):
  TAKE1 = 'TAKE1'
  TAKE2 = 'TAKE2'
  PAY7 = 'PAY7'
  TAKE3 = 'TAKE3'
  PAY3 = 'PAY3'
  EXCHANGE = 'EXCHANGE'
  STEAL2 = 'STEAL2'


class GameStatus(str, Enum):
  INVITE = 'INVITE'
  ACTION = 'ACTION'
  CHALLENGE = 'CHALLENGE'
  CONTRACTION = 'CONTRACTION'
  END = 'END'


class DecisionType(str, Enum):
  PASS = 'PASS'
  CHALLENGE = 'CHALLENGE'