from enum import Enum

MAX_PLAYERS = 5

MONEY_IN_BANK = 50


class ActionType(str, Enum):
  INCOME = 'INCOME'
  FOREIGN_AID = 'FOREIGN_AID'
  COUP = 'COUP'
  TAX = 'TAX'
  ASSASSINATE = 'ASSASSINATE'
  EXCHANGE = 'EXCHANGE'
  STEAL = 'STEAL'


class EffectType(str, Enum):
  TAKE1 = 'TAKE1'
  TAKE2 = 'TAKE2'
  PAY7 = 'PAY7'
  TAKE3 = 'TAKE3'
  PAY3 = 'PAY3'
  EXCHANGE = 'EXCHANGE'
  STEAL2 = 'STEAL2'


class GameType(str, Enum):
  INVITE = 'INVITE'
  ACTION = 'ACTION'
  ACTION_CHECK = 'ACTION_CHECK'
  ACTION_POWER_LOSE = 'ACTION_POWER_LOSE'
  CONTRACTION = 'CONTRACTION'
  CONTRACTION_CHECK = 'CONTRACTION_CHECK'
  CONTRACTION_POWER_LOSE = 'CONTRACTION_POWER_LOSE'
  EFFECT_POWER_LOSE = 'EFFECT_POWER_LOSE'
  END = 'END'


class DecisionType(str, Enum):
  PASS = 'PASS'
  CHALLENGE = 'CHALLENGE'